apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--verbosity=trace",
           "--log-format=color",
            "--context=dir://workspace",
            "--dockerfile=/workspace/Dockerfile",
            "--destination=georgevazj/projects-api:latest"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker
      - name: context
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
    - name: context
      # persistentVolumeClaim:
      #   claimName: dockerfile-claim
      hostPath:
        path: /Users/jorge/Workspace/nodejs/projects-api/kaniko/